# WFM to 1c API
### PlanCreateOrUpdate KT
POST http://localhost:8080/PlanCreateOrUpdate
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 6,
  "Year": 2019,
  "Month": 9,
  "Plan": [
    {"Day": 1,"Minutes": 0,"NightMinutes": 0},
  {"Day": 2,"Minutes": 330,"NightMinutes": 120},
  {"Day": 29,"Minutes": 0,"NightMinutes": 0},
  {"Day":30,"Minutes": 240,"NightMinutes": 0}
  ]
}

### PlanCreateOrUpdate IK
POST http://localhost:8080/PlanCreateOrUpdate
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 1,
  "Year": 2019,
  "Month": 9,
  "Plan": [
    {"Day": 1,"Minutes": 0,"NightMinutes": 0},
    {"Day": 2,"Minutes": 330,"NightMinutes": 120},
    {"Day": 29,"Minutes": 0,"NightMinutes": 0},
    {"Day":30,"Minutes": 240,"NightMinutes": 0}
  ]
}

### PlanDelete IK
POST http://localhost:8080/PlanDelete
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 1,
  "Year": 2019,
  "Month": 9
}

### PlanDelete KT
POST http://localhost:8080/PlanDelete
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 6,
  "Year": 2019,
  "Month": 9
}

### TimeSheetCreateOrUpdate KT
POST http://localhost:8080/TimeSheetCreateOrUpdate
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 6,
  "Year": 2019,
  "Month": 9,
  "Timesheet":
[{"TimePinTypeId":"26","Day":1,"Minutes":0,"NightMinutes":0},
  {"TimePinTypeId":"26","Day":2,"Minutes":0,"NightMinutes":0},
  {"TimePinTypeId":"01","Day":3,"Minutes":60,"NightMinutes":0},
  {"TimePinTypeId":"01","Day":4,"Minutes":60,"NightMinutes":0},
  {"TimePinTypeId":"01","Day":22,"Minutes":279,"NightMinutes":39},
  {"TimePinTypeId":"01","Day":23,"Minutes":563,"NightMinutes":45},
  {"TimePinTypeId":"26","Day":29,"Minutes":0,"NightMinutes":0},
  {"TimePinTypeId":"26","Day":30,"Minutes":0,"NightMinutes":0}],
  "OverTime":{"Minutes":0,"NightMinutes":0}
  }

### TimeSheetCreateOrUpdate IK
POST http://localhost:8080/TimeSheetCreateOrUpdate
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 1,
  "Year": 2019,
  "Month": 9,
  "Timesheet":
  [{"TimePinTypeId":"26","Day":1,"Minutes":0,"NightMinutes":0},
    {"TimePinTypeId":"26","Day":2,"Minutes":0,"NightMinutes":0},
    {"TimePinTypeId":"01","Day":3,"Minutes":60,"NightMinutes":0},
    {"TimePinTypeId":"01","Day":4,"Minutes":60,"NightMinutes":0},
    {"TimePinTypeId":"01","Day":22,"Minutes":279,"NightMinutes":39},
    {"TimePinTypeId":"01","Day":23,"Minutes":563,"NightMinutes":45},
    {"TimePinTypeId":"26","Day":29,"Minutes":0,"NightMinutes":0},
    {"TimePinTypeId":"26","Day":30,"Minutes":0,"NightMinutes":0}],
  "OverTime":{"Minutes":0,"NightMinutes":0}
}
### Error request
POST http://localhost:8080/TimeSheetCreateOrUpdate
Content-Type: application/json

{
  "RequestId":239603,
  "EmployeeId1C": "49bda21f-df49-11e9-90a5-00155d306a3d",
  "EmployeeSourceId": 4,
  "Year": 2019,
  "Month": 9,
  "Timesheet":
  [{"TimePinTypeId":"26","Day":1,"Minutes":0,"NightMinutes":0},
    {"TimePinTypeId":"26","Day":2,"Minutes":0,"NightMinutes":0},
    {"TimePinTypeId":"01","Day":3,"Minutes":60,"NightMinutes":0},
    {"TimePinTypeId":"01","Day":4,"Minutes":60,"NightMinutes":0},
    {"TimePinTypeId":"01","Day":22,"Minutes":279,"NightMinutes":39},
    {"TimePinTypeId":"01","Day":23,"Minutes":563,"NightMinutes":45},
    {"TimePinTypeId":"26","Day":29,"Minutes":0,"NightMinutes":0},
    {"TimePinTypeId":"26","Day":30,"Minutes":0,"NightMinutes":0}],
  "OverTime":{"Minutes":0,"NightMinutes":0}
}

### 1c to WMF API
#GetRequestFrom1C
POST http://localhost:8080/GetRequestFrom1C
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{"EmployeeId1C": "b35e5956-891a-11e9-8a2f-00155d76d140",
  "ActionType": 5,
  "EventType": 5,
  "Actual": 1,
  "Deleted": false,
  "LastName": "Мардовина",
  "FirstName": "Анна",
  "MiddleName": "Алексеевна",
  "BirthDate": "04.12.1990",
  "TabId": "8847",
  "TimeRate": 1,
  "GroupName": "Группа продаж и клиентского обслуживания №2",
  "Group_ID_IN": "ПП147",
  "Title": "Консультант.",
  "TitleId": "ЦБ0000375",
  "LocalityName": "Департамент дистанционного обслуживания г. Барнаул",
  "SiteId": "11",
  "EmployDate": "07.06.2019",
  "DismissDate": "",
  "HomeAddress": "656922, Алтайский край, Барнаул г, Новосиликатный мкр, Новосибирская ул, дом № 26",
  "Telephone": "79132337848"}

### 1c to WMF API
#GetRequestFrom1C
POST http://192.168.88.235:8080/GetRequestFrom1C
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{"EmployeeId1C": "b35e5956-891a-11e9-8a2f-00155d76d140",
  "ActionType": 5,
  "EventType": 5,
  "Actual": 1,
  "Deleted": false,
  "LastName": "Мардовина",
  "FirstName": "Анна",
  "MiddleName": "Алексеевна",
  "BirthDate": "04.12.1990",
  "TabId": "8847",
  "TimeRate": 1,
  "GroupName": "Группа продаж и клиентского обслуживания №2",
  "Group_ID_IN": "ПП147",
  "Title": "Консультант.",
  "TitleId": "ЦБ0000375",
  "LocalityName": "Департамент дистанционного обслуживания г. Барнаул",
  "SiteId": "11",
  "EmployDate": "07.06.2019",
  "DismissDate": "",
  "HomeAddress": "656922, Алтайский край, Барнаул г, Новосиликатный мкр, Новосибирская ул, дом № 26",
  "Telephone": "79132337848"}

###
# GetRequestResultFrom1C
