server:
  # Порт wfm-маршрутизатора (по умолчанию 8080)
  port: 8080

debug: true

# 1c ZUP servers
zup:
  employee-source-id:
    "[ikZup]": 1
    "[cacheMgr]": 2
    "[localUsers]": 3
    "[teEmployee]": 4
    "[ktEmployee]": 5
    "[ktZup]": 6
  servers:
    - url: http://127.0.0.1/zup_kt/hs/wfm1
      login: wfm
      password: none
      employee-source-id: ktZup
    - url: http://127.0.0.1/zup_ik/hs/wfm1
      login: wfm
      password: none
      employee-source-id: ikZup
