server:
  # Порт wfm-маршрутизатора (по умолчанию 8080)
  port: 8080

debug: true

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  version: '@springdoc.version@'
  show-actuator: true

management:
  server:
    port: 8080
    address: 0.0.0.0
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
      base-path: /manage


spring:
  application:
    admin:
      enabled: true

  boot:
    admin:
      client:
        username: ${spring.security.user.name}
        password: ${spring.security.user.name}
        url: "http://localhost:8080"
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.name}
      ui:
        title: "${spring.appliation.name} Admin"

